### ISSUE TITLE
Late-game implementations

### ISSUE THREAD

**Issue by Hampfh** [Hampfh/Datapack_SurvivalGames#9]
When playing the game I've noticed that in the very late game there are only two players/teams alive, almost always at different altitudes, (one blocking himself in the skies and one in the mines). The datapack need some form of implementation to handle this as the current situation allows for camping and thus for the game to continue far beyond the max game duration. I've tested to have the border shrink to one block instead of 20, however this does not solve the problem as it still allows for the players to be on different altitudes.

One thing I have considered is either start spawning mobs around both players or even better, teleport the two into some form of arena (or simply to the same altitude) in order to force action from the players.

**Comment by Geoffry-Skionfinschii** [comment]
The last fight can be an issue, i found it generally extends the game another 20-30 minutes.

Mobspawn rate goes up a large amount anyway due to the smaller spawning area (during games would see at least 10+ mobs in a small area) but additional mobs may not be a bad idea 
(?if they are nametagged or flagged in some way does it count towards mob cap?)

Another way to implement this is to reveal both players with glow every few seconds that lasts only a second or two so they get a short 'blip' of the other player temporarily, and still giving ambushes and traps a chance to work.

Arena is a decent idea, as you can place them at opposite ends and give a few seconds to prepare and force them into combat, and this could be spawned above the lobby (or a few hundred blocks away left or right)

**Comment by Hampfh** [comment]
I actually really like your two last ideas, I guess it could be possible to split this into two periods, first glowing, and then if say maybe a minute has passed and they still haven't killed each other then the players will be teleported

**Comment by Hampfh** [comment]
I'll make a function to detect when the time has exceeded the max, can I assign you to the blip effect?

**Comment by Geoffry-Skionfinschii** [comment]
Yep i can work on the blip, will have it done sometime tomorrow probably :)

**Comment by Hampfh** [comment]
Cool!

**Comment by Hampfh** [comment]
Github is a little weird, turns out I can't assign you unless you comment on the issue, could you do that please. I've opened a separate issue

**Comment by Hampfh** [comment]
The first version of the feature has now been implemented, I've created two new states/substates, end_game and sudden_death. End game is first to trigger and will trigger when the timer reaches `gamemaxduration`. End game will then continue for 2 minutes (subject to change). Finally, sudden death will be activated. This state teleports everybody to a platform in the skies with the dimensions 20x20 here a countdown will start and when it reaches zero the fight begins. This should force players to fight and should prevent games that extend much in time
